services:
  - type: web
    name: vn-stock-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
